name: portfolio_site
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_markdown: ^0.7.0
  url_launcher: ^6.2.4
  flutter_svg: ^1.1.6
  web: ^0.5.1 
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/games/
    - assets/images/other/
    - assets/images/sit/
    - assets/projects.json
    - assets/page_config.json
    - assets/landing_page.json
